apiVersion: apps/v1
kind: Deployment
metadata:
  name: valheim-server
  labels:
    app: valheim-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valheim-server
  template:
    metadata:
      labels:
        app: valheim-server
    spec:
      containers:
      - name: valheim-server
        image: benenb/valheim-box64:v1
        ports:
        - name: game
          containerPort: 2456
          protocol: UDP
        - name: query
          containerPort: 2457
          protocol: UDP
        env:
        - name: VALHEIM_SERVER_NAME
          value: "Benji's Server"
        - name: VALHEIM_WORLD_NAME
          value: "ValheimBox64"
        - name: VALHEIM_ISPUBLIC
          value: "true"
        - name: VALHEIM_CROSSPLAY
          value: "true"
        - name: VALHEIM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valheim-server-secret
              key: server-password
              optional: true
        volumeMounts:
        - name: valheim-data
          mountPath: /config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      volumes:
      - name: valheim-data
        persistentVolumeClaim:
          claimName: valheim-server-pvc

